item {
  id: 1
  name: "u16healthy"
}
item {
  id: 2
  name: "u15healthy"
}
item {
  id: 3
  name: "u14healthy"
}
item {
  id: 4
  name: "u13healthy"
}
item {
  id: 5
  name: "u12healthy"
}
item {
  id: 6
  name: "u11healthy"
}
item {
  id: 7
  name: "u10healthy"
}
item {
  id: 8
  name: "u9healthy"
}
item {
  id: 9
  name: "u8healthy"
}
item {
  id: 10
  name: "u7healthy"
}
item {
  id: 11
  name: "u6healthy"
}
item {
  id: 12
  name: "u5healthy"
}
item {
  id: 13
  name: "u4healthy"
}
item {
  id: 14
  name: "u3healthy"
}
item {
  id: 15
  name: "u2healthy"
}
item {
  id: 16
  name: "u1healthy"
}
item {
  id: 17
  name: "i16healthy"
}
item {
  id: 18
  name: "i15healthy"
}
item {
  id: 19
  name: "i14healthy"
}
item {
  id: 20
  name: "i13healthy"
}
item {
  id: 21
  name: "i12healthy"
 }
item {
  id: 22
  name: "i11healthy"
}
item {
  id: 23
  name: "i10healthy"
}
item {
  id: 24
  name: "i9healthy"
}
item {
  id: 25
  name: "i8healthy"
}
item {
  id: 26
  name: "i7healthy"
}
item {
  id: 27
  name: "i6healthy"
}
item {
  id: 28
  name: "i5healthy"
}
item {  
  id: 29
  name: "i4healthy"
}
item {
  id: 30
  name: "i3healthy"
}
item {
  id: 31
  name: "i2healthy"
}
item {
  id: 32
  name: "i1healthy"
}
item {
  id: 33
  name: "u16loss"

}
item {
  id: 34
  name: "u15loss"
}
item {
  id: 35
  name: "u14loss"
}
item {
  id: 36
  name: "u13loss"
 
}
item {
  id: 37
  name: "u12loss"
}
item {
  id: 38
  name: "u11loss"
}
item {
   id: 39
  name: "u10loss"
}
item {
  id: 40
  name: "u9loss"
}
item {
  id: 41
  name: "u8loss"
}
item {
  id: 42
  name: "u7loss"
}
item {
  id: 43
  name: "u6loss"
}
item {
  id: 44
  name: "u5loss"
}
item {
  id: 45
  name: "u4loss"
}
item {
  id: 46
  name: "u3loss"
}
item {
  id: 47
  name: "u2loss"
}
item {
  id: 48
  name: "u1loss"
}
item {
  id: 49
  name: "i16loss"
}
item {
  id: 50
  name: "i15loss"
}
item {
  id: 51
  name: "i14loss"
}
item {
  id: 52
  name: "i13loss"
}
item {
  id: 53
  name: "i12loss"
}
item {
  id: 54
  name: "i11loss"
 
}
item {
  id: 55
  name: "i10loss"
}
item {
  id: 56
  name: "i9loss"
}
item {
  id: 57
  name: "i8loss"
}
item {
  id: 58
  name: "i7loss"
}
item {
  id: 59
  name: "i6loss"
}
item {
  id: 60
  name: "i5loss"
}
item {
  id: 61
  name: "i4loss"
}
item {
  id: 62
  name: "i3loss"
}
item {
  id: 63
  name: "i2loss"
}
item {
  id: 64
  name: "i1loss"
}
item {
  id: 65
  name: "u16chipped"
}
item {
  id: 66
  name: "u15chipped"
}
item {
  id: 67
  name: "u14chipped"
}
item {
  id: 68
  name: "u13chipped"
}
item {
  id: 69
  name: "u12chipped"
}
item {
  id: 70
  name: "u11chipped"
}
item {
  id: 71
  name: "u10chipped"
}
item {
  id: 72
  name: "u9chipped"
  }
item {
  id: 73
  name: "u8chipped"
}
item {
  id: 74
  name: "u7chipped"
}
item {
  id: 75
  name: "u6chipped"
}
item {
  id: 76
  name: "u5chipped"
}
item {
  id: 77
  name: "u4chipped"
}
item {
  id: 78
  name: "u3chipped"
}
item {
  id: 79
  name: "u2chipped"
}
item {
  id: 80
  name: "u1chipped"
}
item {
  id: 81
  name: "i16chipped"
}
item {
  id: 82
  name: "i15chipped"
}
item {
  id: 83
  name: "i14chipped"
}
item {
  id: 84
  name: "i13chipped"
}
item {
  id: 85
  name: "i12chipped"
}
item {
  id: 86
  name: "i11chipped"
}
item {
  id: 87
  name: "i10chipped"
}
item {
  id: 88
  name: "i9chipped"
}
item {
  id: 89
  name: "i8chipped"
}
item {
  id: 90
  name: "i7chipped"
}
item {
  id: 91
  name: "i6chipped"
}
item {
  id: 92
  name: "i5chipped"
}
item {
  id: 93
  name: "i4chipped"
}
item {
  id: 94
  name: "i3chipped"
}
item {
  id: 95
  name: "i2chipped"
}
item {
  id: 96
  name: "i1chipped"
}
item {
  id: 97
  name: "u16decay"
}
item {
  id: 98
  name: "u15decay"
}
item {
  id: 99
  name: "u14decay"
}
item {
  id: 100
  name: "u13decay"
}
item {
  id: 101
  name: "u12decay"
}
item {
  id: 102
  name: "u11decay"
}
item {
  id: 103
  name: "u10decay"
}
item {
  id: 104
  name: "u9decay"
}
item {
  id: 105
  name: "/u8decay"
}
item {
  id: 106
  name: "u7decay"
}
item {
  id: 107
  name: "u6decay"
}
item {
  id: 108
  name: "u5decay"
}
item {
  id: 109
  name: "u4decay"
}
item {
  id: 110
  name: "u3decay"
}
item {
  id: 111
  name: "u2decay"
}
item {
  id: 112
  name: "u1decay"
}
item {
  id: 113
  name: "i16decay"
}
item {
  id: 114
  name: "i15decay"
}
item {
  id: 115
  name: "i14decay"
}
item {
  id: 116
  name: "i13decay"
}
item {
  id: 117
  name: "i12decay"
}
item {
  id: 118
  name: "i11decay"
}
item {
  id: 119
  name: "i10decay"
}
item {
  id: 120
  name: "i9decay"
}
item {
  id: 121
  name: "i8decay"
}
item {
  id: 122
  name: "i7decay"
}
item {
  id: 123
  name: "i6decay"
}
item {
  id: 124
  name: "i5decay"
}
item {
  id: 125
  name: "i4decay"
}
item {
  id: 126
  name: "i3decay"
}
item {
  id: 127
  name: "i2decay"
}
item {
  id: 128
  name: "i1decay"
}